---
title: "Deliverable 2025"
author: "Catharina Clark"
date: "2025-02-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages and Dataset

```{r Project}

library(rmarkdown)
library(readxl)
library(ggplot2)
library(tidyverse)
library(dplyr)

small_mammal_data <- read_xlsx("Renosterveld_Sherman trap data_Cat.xlsx")

head(small_mammal_data)
view(small_mammal_data)
summary(small_mammal_data)
```
## Selection of Columns for Analysis and Use

```{r}

alt_data <- small_mammal_data %>% select(`Trap station`, Species)
class(alt_data$`Trap station`)

```

## Convert Trap Station to a Factor

```{r}

alt_data$`Trap station` <- as.factor(alt_data$`Trap station`)
class(alt_data$`Trap station`)

view(alt_data)

```
## New Table of Data (Made Tidy)

```{r}

unique_counts_data <- small_mammal_data %>%
  count(`Trap station`)

print(unique_counts_data)

total_captures <- sum(unique_counts_data$n)

unique_counts_data <- unique_counts_data%>%
  mutate(`Captures Percentages` = round((n / total_captures)*100,2))

view(unique_counts_data)

```

## Plots

```{r small_mammal_data, echo=FALSE}

ggplot(unique_counts_data, aes(x = `Trap station`, y = `Captures Percentages`)) +
  geom_bar(stat = "identity") + 
  theme_minimal() + 
  labs(title = "Bar Plot of Percentage of Small Mammals Captured per Trap Station", 
       x = "Trap Station", 
       y = "Capture Percentage")


```

